"""ecommerce kickoff, user and product table

Revision ID: 6b66c49a1818
Revises: dbb9e6c51697
Create Date: 2018-02-03 03:57:15.088583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b66c49a1818'
down_revision = 'dbb9e6c51697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mrp', sa.Integer(), nullable=True),
    sa.Column('offer_price', sa.Integer(), nullable=True),
    sa.Column('cod_eligible', sa.Boolean(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.Column('returnable', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('district', sa.String(), nullable=True))
    op.add_column('user', sa.Column('kisan_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'kisan_id')
    op.drop_column('user', 'district')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    op.drop_table('product')
    # ### end Alembic commands ###
